name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - matplotlib
  - slycot
  - control
  - graphviz
  - xdg
  - xarray
  - xlrd
  - PyQt5
  - fortran-magic
  - bokeh
  - cython
  - numba
  - rpy2
  - tzlocal
  - simplegeneric
  - pip:
    - pysfg
    - vibration_toolbox
    - PyQt5
    - cffi_magic
