name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - openpyxl
  - fortran-magic
  - bokeh
  - cython
  - numba
  - widgetsnbextension
  - pip
  - pip:
    - -r requirements.txt
