name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - ipython
  - matplotlib
  - slycot
  - control
  - graphviz
  - xdg
  - xarray
  - xlrd
  - fortran-magic
  - bokeh
  - cython
  - numba
  - rise
  - tzlocal
  - simplegeneric
  - widgetsnbextension
  - jupyter_nbextensions_configurator
  - pip
  - nodejs
  - r
  - pip:
    - -r requirements.txt
    - --user
