name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - ipython
  - matplotlib
  - slycot
  - control
  - graphviz
  - xdg
  - xarray
  - xlrd
  - fortran-magic
  - bokeh
  - cython
  - numba
  - rpy2
  - tzlocal
  - simplegeneric
  - widgetsnbextension
  - pip:
    - -r requirements.txt
